#!/usr/bin/env python3
"""
Publication HTML Generator

Reads publications.yaml and regenerates the block between the
PUBLICATIONS_START / PUBLICATIONS_END markers in index.html.
Usage: python paper_gen.py
"""

from html import escape
from pathlib import Path

import yaml

START_MARKER = "<!-- PUBLICATIONS_START -->"
END_MARKER = "<!-- PUBLICATIONS_END -->"
SCHOLAR_NOTE = "* equal contribution"


def load_publications(yaml_path: Path) -> list:
    with open(yaml_path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f).get("publications", [])


def author_names(authors: list, me_style: str) -> str:
    parts = []
    for author in authors:
        name = escape(author["name"])
        star = "*" if author.get("equal") else ""
        if author.get("is_me"):
            parts.append(
                f"<b>{name}{star}</b>" if me_style == "bold" else f"<u>{name}</u>{star}"
            )
        else:
            url = author.get("url")
            linked = (
                f'<a class="author" href="{escape(url, quote=True)}">{name}</a>'
                if url
                else name
            )
            parts.append(linked + star)
    return ", ".join(parts)


def link_list(links: dict) -> list:
    links = links or {}
    out = []
    if links.get("paper"):
        label = "arXiv" if "arxiv.org" in links["paper"] else "Paper"
        out.append((label, links["paper"]))
    for key, label in (
        ("project", "Project"),
        ("github", "Code"),
        ("video", "Video"),
        ("medium", "Blog"),
    ):
        if links.get(key):
            out.append((label, links[key]))
    return [f'<a href="{escape(url, quote=True)}">[{label}]</a>' for label, url in out]


def media_html(pub: dict) -> str:
    thumb = escape(pub["thumb"], quote=True)
    if pub.get("thumb_video"):
        video = escape(pub["thumb_video"], quote=True)
        return (
            f'<video src="{video}" poster="{thumb}" autoplay muted loop playsinline '
            f'preload="metadata"></video>'
        )
    return (
        f'<img src="{thumb}" alt="{escape(pub["title"], quote=True)}" loading="lazy">'
    )


def selected_row(pub: dict) -> str:
    chip = escape(pub.get("venue_short") or pub["venue"])
    tldr = (
        f'\n      <p class="tldr">{escape(pub["description"].strip())}</p>'
        if pub.get("description")
        else ""
    )
    return f"""
  <div class="pub">
    <div class="media">{media_html(pub)}</div>
    <div>
      <p class="ptitle">{escape(pub["title"])}</p>
      <p class="pauthors">{author_names(pub.get("authors", []), "bold")}</p>
      <span class="pmeta"><span class="chip">{chip}</span><span class="plinks">{"".join(link_list(pub.get("links")))}</span></span>{tldr}
    </div>
  </div>"""


def full_list_item(pub: dict) -> str:
    links = "".join(link_list(pub.get("links")))
    links_html = f'<span class="vn">{links}</span>' if links else ""
    return (
        f'    <li><span class="tag">[{escape(pub["tag"])}]</span><span>'
        f'<span class="pt">{escape(pub["title"])}</span>'
        f'<span class="au">{author_names(pub.get("authors", []), "underline")}</span>'
        f'<span class="vn">{escape(pub["venue"])}</span>{links_html}</span></li>'
    )


def generate_publications_html(publications: list) -> str:
    selected = [p for p in publications if p.get("selected")]
    rows = "\n".join(selected_row(p) for p in selected)
    items = "\n".join(full_list_item(p) for p in publications)
    return f"""{START_MARKER}
  <!-- Auto-generated by paper_gen.py from publications.yaml. Do not edit by hand. -->
  <h2>Selected Research</h2>
  <p class="scholar">{escape(SCHOLAR_NOTE)}</p>
{rows}

  <details>
  <summary>All publications ({len(publications)})</summary>
  <ul class="pubs">
{items}
  </ul>
  </details>
  {END_MARKER}"""


def update_index_html(html_path: Path, publications_html: str) -> bool:
    content = html_path.read_text(encoding="utf-8")
    start = content.find(START_MARKER)
    end = content.find(END_MARKER)
    if start == -1 or end == -1:
        print(f"ERROR: add {START_MARKER} and {END_MARKER} markers to {html_path}")
        return False
    html_path.write_text(
        content[:start] + publications_html + content[end + len(END_MARKER) :],
        encoding="utf-8",
    )
    return True


def main() -> int:
    script_dir = Path(__file__).parent
    publications = load_publications(script_dir / "publications.yaml")
    selected = sum(1 for p in publications if p.get("selected"))
    print(f"Found {len(publications)} publications ({selected} selected)")
    if update_index_html(
        script_dir / "index.html", generate_publications_html(publications)
    ):
        print("✓ Successfully updated index.html")
        return 0
    print("✗ Failed to update index.html")
    return 1


if __name__ == "__main__":
    exit(main())
